site_name: My documentation
theme:
  name: material
  favicon: img/dna-solid.svg
  logo: img/LOGO2.svg
  features:
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - header.autohide
  - announce.dismiss
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - nvigation.tracking
  - search.highlight
  - search.share
  - search.suggest

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default 
      primary: blue
      accent: deep orange    
      toggle: 
        icon: material/weather-sunny
        name: Sitch to dark mode 


  plugins: 
    - typeset
    - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
copyright: 
  Copyright © 2024 <a href="https://github.com/dcosimber" target="_blank" rel="noopener">Daniel Costas</a>